version: '3'
services:
  run:
    build:
      context: .
      dockerfile: run.dockerfile
    environment:
      - DEV=true
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service_account.json
    ports:
      - "8080:8080"
    depends_on:
      - cuda

  cuda:
    build:
      context: .
      dockerfile: cuda.dockerfile
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - DEV=true
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service_account.json
    ports:
      - "5000:5000"
